### ISSUE TITLE
Adding a repository is not working

### ISSUE THREAD

**Issue by alexschroeter** [arkitektio/kabinet#1]
Wasn't able to add `https://github.com/alexschroeter/tensorflow-test` to Kabinet to be able to use it in `apptainer-deployer` with GPU support.

**Comment by jhnnsrs** [comment]
I fixed so that it accepts also a github url, and shows a proper error message if its incorrect. You can pull the latest changes

https://github.com/alexschroeter/tensorflow-test is however not a correct arkitekt-next repo (it doesn't container the .arkitekt-next folder ;)

**Comment by alexschroeter** [comment]
Good point. I didn't push the changes yet. O.o

**Comment by alexschroeter** [comment]
`https://github.com/alexschroeter/tensorflow-test` is the repository and I get the following error:
`Invalid kabinet.yml. Is this a kabinet repo?`

**Comment by alexschroeter** [comment]
Error was due to diverging selector definition between the client and server (type → kind).
